baseURL: https://www.example.com
languageCode: en-us
title: Laura Lee-Chu
theme: hugo-digital-garden-theme
params:
  description: I'm based in Toronto, Canada and I'm currently seeking internship opportunities for summer 2023! 
  googleAnalytics: ''
  initials: L
  name: Laura Lee-Chu
  social:
    - icon: fab fa-linkedin-in
      link: 'https://www.linkedin.com/in/lauraleechu/'
      name: LinkedIn
menu:
  main:
    - name: Work
      url: /projects/
      weight: 2
    - name: Resume
      url: /resume/
      weight: 3
    - name: About
      url: /about/
      weight: 1
taxonomies:
  project_tags: project_tags
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: yes
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    renderer:
      unsafe: yes
  highlight:
    style: monokailight
